export enum FcmTopics {
  PROMO_CODE_CREATED = 'PROMO_CODE_CREATED',
}

export enum NotificationsType {
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_TRACKING = 'ORDER_TRACKING',
  NEW_PROMO_CODE = 'NEW_PROMO_CODE',
  ORDER_WAITING_FOR_ADMIN = 'ORDER_WAITING_FOR_ADMIN',
}
